# Dependabot configuration for automatic security patches
version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    reviewers:
      - "sethcarp8"
    assignees:
      - "sethcarp8"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    # Group minor and patch updates together
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Security updates should be created immediately
    ignore:
      # Ignore major version updates for now (review manually)
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    reviewers:
      - "sethcarp8"
    assignees:
      - "sethcarp8"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Enable version updates for Docker (if you add Docker later)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    reviewers:
      - "sethcarp8"
    assignees:
      - "sethcarp8"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "docker" 